load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "euclidean_cluster_config_proto",
    srcs = ["euclidean_cluster_config.proto"],
)

apollo_package()